### ISSUE TITLE
model.create(Unique constraint failed on the constraint: `PRIMARY` baileys-store

### ISSUE THREAD

**Issue by casudinlix** [ookamiiixd/baileys-store#3]
hi, I do individual messaging.
however, after I checked the terminal an error appeared like the following:
![image (45)](https://user-images.githubusercontent.com/15974968/214758261-a0acb6f9-1389-4ae1-ba51-df095ad4ce29.png)

`{"level":50,"time":1674705594919,"pid":183106,"hostname":"casudin-local","err":{"type":"PrismaClientKnownRequestError","message":"\nInvalid `model.create()` invocation in\n/home/casudin/www/project/wa-api-new/node_modules/@ookamiiixd/baileys-store/dist/handlers/message.js:79:27\n\n  76         },\n  77     },\n  78 }),\n→ 79 model.create(\nUnique constraint failed on the constraint: `PRIMARY`","stack":"Error: \nInvalid `model.create()` invocation in\n/home/casudin/www/project/wa-api-new/node_modules/@ookamiiixd/baileys-store/dist/handlers/message.js:79:27\n\n  76         },\n  77     },\n  78 }),\n→ 79 model.create(\nUnique constraint failed on the constraint: `PRIMARY`\n    at RequestHandler.handleRequestError (/home/casudin/www/project/wa-api-new/node_modules/@prisma/client/runtime/index.js:34869:13)\n    at RequestHandler.handleAndLogRequestError (/home/casudin/www/project/wa-api-new/node_modules/@prisma/client/runtime/index.js:34841:12)\n    at RequestHandler.request (/home/casudin/www/project/wa-api-new/node_modules/@prisma/client/runtime/index.js:34836:12)\n    at async PrismaClient._request (/home/casudin/www/project/wa-api-new/node_modules/@prisma/client/runtime/index.js:35926:16)\n    at async Promise.all (index 1)\n    at async EventEmitter.update (/home/casudin/www/project/wa-api-new/node_modules/@ookamiiixd/baileys-store/dist/handlers/message.js:68:17)","code":"P2002","clientVersion":"4.7.1","meta":{"target":"PRIMARY"}},"msg":"An error occured during message update"}`

**Comment by deadlinecode** [comment]
@casudinlix 
You can mby try use my package
I just updated it
Its mby an alternative
https://www.npmjs.com/package/baileys-bottle
